function odes = R_0(beta_m,beta_h,theta_m,theta_h,mu_m,gamma_h,mu_h)
%R_0
%    ODES = R_0(BETA_M,BETA_H,THETA_M,THETA_H,MU_M,GAMMA_H,MU_H)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    02-Oct-2019 17:22:55

odes = sqrt((beta_h.*beta_m.*theta_h.*theta_m)./(mu_m.*(gamma_h+mu_h).*(mu_h+theta_h).*(mu_m+theta_m)));
